variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    -s .m2/settings.xml
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    -X

cache:
  paths:
    - .m2/repository

.documents-common:
  tags:
    - jdk-21
  rules:
    - changes:
        - '../documents/*'

documents-test:
  extends: .documents-common
  stage: test
  script:
    - echo "Testing documents app"
    - 'cd documents && ./mvnw test $MAVEN_CLI_OPTS -DskipTests $MAVEN_OPTS'

documents-deploy:
  extends: .documents-common
  stage: deploy
  script:
    - echo "Deploy documents app"
    - 'cd documents && ./mvnw deploy $MAVEN_CLI_OPTS -DskipTests $MAVEN_OPTS'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH