variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
  MVNW: 'cd documents && ./mvnw'

cache:
  paths:
    - .m2/repository

.documents-common:
  tags:
    - jdk-21
  rules:
    - changes:
        - '../documents/*'

documents-test:
  extends: .documents-common
  stage: test
  script:
    - echo "Testing documents app"
    - '$MVNW $MAVEN_CLI_OPTS test -s .m2/settings.xml -DskipTests -X'

documents-deploy:
  extends: .documents-common
  stage: deploy
  script:
    - echo "Deploy documents app"
    - '$MVNW $MAVEN_CLI_OPTS deploy -s .m2/settings.xml -DskipTests -X'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH