variables:
  NEXUS_HOST: 'gitlab.local'
  NEXUS_DOCKER_PORT: 8100
  NEXUS_M2_PORT: 8099
  NEXUS_USERNAME: 'deployment'
  NEXUS_PASSWORD: '1561dc49-dc73-4ede-9fb4-f2eab4efe539'
  SONAR_HOST_URL: 'http://gitlab.local:9000'
  SONAR_LOGIN: 'sqp_28e7966d7a7b4b39ea2f8bc44d9bbab61a3acccd'

top-level-job:
  stage: build
  tags:
    - jdk-21
  script:
    - echo "Hello world..."

include:
  - local: '/image-generation-manager/.gitlab-ci.yml'
    rules:
      - changes:
          - 'image-generation-manager/**/*'
  - local: '/image-generator/.gitlab-ci.yml'
    rules:
      - changes:
          - 'image-generator/**/*'
  - local: '/documents/.gitlab-ci.yml'
    rules:
      - changes:
          - 'documents/**/*'