version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:22'
    volumes:
      - './home/config:/etc/gitlab:rw'
      - './home/logs:/var/log/gitlab:rw'
      - './home/data:/var/opt/gitlab:rw'
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine3.19-bleeding
    container_name: gitlab-runner
    depends_on:
      gitlab:
        condition: service_healthy
    volumes:
      - '//var/run/docker.sock:/var/run/docker.sock'
      - '//var/lib/docker:/var/lib/docker'
      - '//usr/local/bin/docker:/usr/bin/docker'
      - './home/gitlab-runner:/etc/gitlab-runner:rw'

  nexus:
    image: sonatype/nexus3:3.71.0-alpine
    ports:
      - "8099:8081"
    volumes:
      - './nexus:/nexus-data:rw'