version: '3.8'

services:
  app-image-generation-manager:
    image: dev-cluster:8100/image-generation-manager:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    networks:
      - apps-network
    environment:
      APP_HOST: dev-cluster
      APP_PORT: 8081
      DATASOURCE_HOST: ${DATASOURCE_HOST}
      DATASOURCE_PORT: ${DATASOURCE_PORT}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      KAFKA_SERVER_HOST: ${KAFKA_SERVER_HOST}
      KAFKA_SERVER_PORT: ${KAFKA_SERVER_PORT}
      LOKI_HOST: ${LOKI_HOST}
      TEMPO_ZIPKIN_ENDPOINT: ${TEMPO_ZIPKIN_ENDPOINT}
  app-image-generator:
    image: dev-cluster:8100/image-generator:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    networks:
      - apps-network
    environment:
      APP_PORT: 8082
      KAFKA_SERVER_HOST: ${KAFKA_SERVER_HOST}
      KAFKA_SERVER_PORT: ${KAFKA_SERVER_PORT}
      INTEGRATION_DOCUMENTS_SERVER_HOST: documents
      INTEGRATION_DOCUMENTS_SERVER_PORT: 8083
      LOKI_HOST: ${LOKI_HOST}
      TEMPO_ZIPKIN_ENDPOINT: ${TEMPO_ZIPKIN_ENDPOINT}
  app-documents:
    image: dev-cluster:8100/documents:0.0.1-SNAPSHOT
    hostname: documents
    ports:
      - "8083:8083"
    networks:
      - apps-network
    volumes:
      - './documents/filestorage:/workspace/uploads:rw'
    environment:
      APP_HOST: dev-cluster
      APP_PORT: 8083
      DATASOURCE_HOST: ${DATASOURCE_HOST}
      DATASOURCE_PORT: ${DATASOURCE_PORT}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      LOKI_HOST: ${LOKI_HOST}
      TEMPO_ZIPKIN_ENDPOINT: ${TEMPO_ZIPKIN_ENDPOINT}

networks:
  apps-network:
    external:
      name: dev-cluster-network

