cache:
  paths:
    - .m2/repository

.image-generation-manager-common:
  tags:
    - jdk-21
  rules:
    - &rule_changes
      changes:
        - 'image-generation-manager/**/*'

image-generation-manager-test:
  rules:
    - *rule_changes
  extends: .image-generation-manager-common
  stage: test
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/image-generation-manager/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - echo "Testing image-generation-manager app"
    - 'cd image-generation-manager && ./mvnw test sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST_URL $MAVEN_CLI_OPTS $MAVEN_OPTS'

image-generation-manager-deploy:
  rules:
    - *rule_changes
    - if: "$CI_MERGE_REQUEST_IID"
  extends: .image-generation-manager-common
  stage: deploy
  script:
    - echo "Deploy image-generation-manager app"
    - 'cd image-generation-manager && ./mvnw deploy -DskipTests $MAVEN_CLI_OPTS $MAVEN_OPTS'