variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    -s .m2/settings.xml
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

cache:
  paths:
    - .m2/repository

.image-generation-manager-common:
  tags:
    - jdk-21

image-generation-manager-test:
  extends: .image-generation-manager-common
  stage: test
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - echo "Testing image-generation-manager app"
    - 'cd image-generation-manager && ./mvnw test sonar:sonar -Dsonar.login=${SONAR_LOGIN} -Dsonar.host.url=${SONAR_HOST_URL} ${MAVEN_CLI_OPTS} ${MAVEN_OPTS} -X'

image-generation-manager-deploy:
  extends: .image-generation-manager-common
  stage: deploy
  script:
    - echo "Deploy image-generation-manager app"
    - 'cd image-generation-manager && ./mvnw deploy -DskipTests ${MAVEN_CLI_OPTS} ${MAVEN_OPTS}'