version: '3.9'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8080:8080"
    networks:
      - monitoring-network
    restart: unless-stopped
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      LOGGING_LEVEL_ROOT: 'DEBUG'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_SERVER_HOST}:${KAFKA_SERVER_PORT}
      
networks:
  monitoring-network:
    external:
      name: dev-cluster-network