version: '3.1'

services:
  app-image-generation-manager:
    image: gitlab.local:8100/image-generation-manager:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
  app-image-generator:
    image: gitlab.local:8100/image-generator:0.0.1-SNAPSHOT
    depends_on:
      - postgres
      - kafka
  app-documents:
    image: gitlab.local:8100/documents:0.0.1-SNAPSHOT
    hostname: documents
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - kafka
    volumes:
      - './documents/filestorage:/workspace/uploads:rw'
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - './postgres:/docker-entrypoint-initdb.d'
  kafka:
    image: apache/kafka:3.8.0
    hostname: broker
    restart: always
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - kafka
    links:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      LOGGING_LEVEL_ROOT: 'DEBUG'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:19092