concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-runner-default"
  url = "http://gitlab.local:8929"
  id = 2
  token = "glrt-zKk-UBm-2ogY-AspNAd3"
  token_obtained_at = 2024-08-16T17:54:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  tags = "jdk 21"
  runUntagged = false
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    Insecure = false
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v17.3.0"
    extra_hosts = ["gitlab.local:192.168.100.15"]
    tls_verify = false
    image = "eclipse-temurin:21.0.4_7-jdk"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
    network_mtu = 0
