version: '3.9'
services:
  gitlab:
    image: gitlab/gitlab-ce:17.3.0-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:22'
    networks:
      - ci-network
    volumes:
      - './gitlab/master/config:/etc/gitlab:rw'
      - './gitlab/master/logs:/var/log/gitlab:rw'
      - './gitlab/master/data:/var/opt/gitlab:rw'
    shm_size: '512m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://dev-cluster:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['initial_root_password'] = 'r5YzGA7+fEjs8kcTQdr8Er4o6ebURRwTf4kR3M7Lmn4='
  gitlab-runner:
    image: gitlab/gitlab-runner:v17.3.0
    container_name: gitlab-runner
    networks:
      - ci-network
    depends_on:
      gitlab:
        condition: service_healthy
    volumes:
      - '//var/run/docker.sock:/var/run/docker.sock'
      - './gitlab/runner:/etc/gitlab-runner:rw'

  nexus:
    image: sonatype/nexus3:3.71.0-alpine
    ports:
      - "8099:8081"
      - "8100:8100"
    networks:
      - ci-network
    volumes:
      - './nexus:/nexus-data:rw'

  sonarqube:
    image: sonarqube:9.9.6-community
    hostname: sonarqube
    container_name: sonarqube
    read_only: true
    networks:
      - ci-network
    depends_on:
      sonar-db:
        condition: service_started
    volumes:
      - './sonarqube/data:/opt/sonarqube/data'
      - './sonarqube/extensions:/opt/sonarqube/extensions'
      - './sonarqube/logs:/opt/sonarqube/logs'
      - './sonarqube/temp:/opt/sonarqube/temp'
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      
  sonar-db:
    image: postgres:15.2
    hostname: sonar-db
    container_name: sonar-db
    networks:
      - ci-network
    volumes:
      - './sonarqube/postgresql:/var/lib/postgresql'
      - './sonarqube/postgresql/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
      
networks:
  ci-network:
    external:
      name: dev-cluster-network